//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Titles.DAL.EntityModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class TitleDetail
    {
        public int TitleId { get; set; }
        public string TitleName { get; set; }
        public string GenreName { get; set; }
        public string Award { get; set; }
        public string AwardCompany { get; set; }
        public Nullable<int> AwardYear { get; set; }
    }
}
